// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Fmi2Pntq46d-b1sZUeub-8bY3MlAbv8',
    appId: '1:439260506934:web:eaa892d0727fa3a793e197',
    messagingSenderId: '439260506934',
    projectId: 'drp-37',
    authDomain: 'drp-37.firebaseapp.com',
    storageBucket: 'drp-37.firebasestorage.app',
    measurementId: 'G-CG33XTW6SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMis1Dwv_rRHOA1L_Or7Em3yBKGFde7O0',
    appId: '1:439260506934:android:9b463a8c6b6b869f93e197',
    messagingSenderId: '439260506934',
    projectId: 'drp-37',
    storageBucket: 'drp-37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBr5_tBV7ySvNql_BVEgf5Uf6oggCbLQ4',
    appId: '1:439260506934:ios:2b29167f69cbe6ac93e197',
    messagingSenderId: '439260506934',
    projectId: 'drp-37',
    storageBucket: 'drp-37.firebasestorage.app',
    iosBundleId: 'com.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBr5_tBV7ySvNql_BVEgf5Uf6oggCbLQ4',
    appId: '1:439260506934:ios:fe6237cb2a6a1dec93e197',
    messagingSenderId: '439260506934',
    projectId: 'drp-37',
    storageBucket: 'drp-37.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Fmi2Pntq46d-b1sZUeub-8bY3MlAbv8',
    appId: '1:439260506934:web:80c56053327c689293e197',
    messagingSenderId: '439260506934',
    projectId: 'drp-37',
    authDomain: 'drp-37.firebaseapp.com',
    storageBucket: 'drp-37.firebasestorage.app',
    measurementId: 'G-QFF8189FRR',
  );
}
